// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddPadding(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function AdjustBitrate(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:boolean):Promise<void>;

export function AdjustVolume(arg1:string,arg2:string,arg3:number):Promise<void>;

export function CancelOperation():Promise<void>;

export function ChangeResolution(arg1:string,arg2:string,arg3:number,arg4:number,arg5:string):Promise<void>;

export function ConvertFormat(arg1:string,arg2:string):Promise<void>;

export function CropVideo(arg1:string,arg2:string,arg3:number,arg4:number,arg5:number,arg6:number):Promise<void>;

export function DetectHardwareEncoder():Promise<string>;

export function ExtractAudio(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ExtractThumbnail(arg1:string):Promise<string>;

export function GetDefaultOutputName(arg1:string,arg2:string):Promise<string>;

export function GetDiskSpace():Promise<Array<models.MountPoint>>;

export function GetFileInfo(arg1:string):Promise<models.FileInfo>;

export function PreviewCommand(arg1:string,arg2:string,arg3:string,arg4:Record<string, any>):Promise<string>;

export function SelectInputFile():Promise<string>;

export function SelectOutputFile(arg1:string):Promise<string>;

export function TrimRange(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function TrimStart(arg1:string,arg2:string,arg3:number):Promise<void>;

export function TrimToLength(arg1:string,arg2:string,arg3:number):Promise<void>;
