// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AdjustBitrate(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['AdjustBitrate'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function AdjustVolume(arg1, arg2, arg3) {
  return window['go']['main']['App']['AdjustVolume'](arg1, arg2, arg3);
}

export function CancelOperation() {
  return window['go']['main']['App']['CancelOperation']();
}

export function ChangeResolution(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ChangeResolution'](arg1, arg2, arg3, arg4, arg5);
}

export function ConvertFormat(arg1, arg2) {
  return window['go']['main']['App']['ConvertFormat'](arg1, arg2);
}

export function CropVideo(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['CropVideo'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function DetectHardwareEncoder() {
  return window['go']['main']['App']['DetectHardwareEncoder']();
}

export function ExtractAudio(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExtractAudio'](arg1, arg2, arg3);
}

export function ExtractThumbnail(arg1) {
  return window['go']['main']['App']['ExtractThumbnail'](arg1);
}

export function GetDefaultOutputName(arg1, arg2) {
  return window['go']['main']['App']['GetDefaultOutputName'](arg1, arg2);
}

export function GetDiskSpace() {
  return window['go']['main']['App']['GetDiskSpace']();
}

export function GetFileInfo(arg1) {
  return window['go']['main']['App']['GetFileInfo'](arg1);
}

export function PreviewCommand(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['PreviewCommand'](arg1, arg2, arg3, arg4);
}

export function SelectInputFile() {
  return window['go']['main']['App']['SelectInputFile']();
}

export function SelectOutputFile(arg1) {
  return window['go']['main']['App']['SelectOutputFile'](arg1);
}

export function TrimRange(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TrimRange'](arg1, arg2, arg3, arg4);
}

export function TrimStart(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrimStart'](arg1, arg2, arg3);
}

export function TrimToLength(arg1, arg2, arg3) {
  return window['go']['main']['App']['TrimToLength'](arg1, arg2, arg3);
}
